Repository itssamuelrowe/kush, pull requests merged in 2020-06, with the labels that each got.

#1 Dump recognized tokens
  include/kush/token.h
  source/compiler.c
  source/lexer.c
  source/token.c
Labels: enhancement

#3 Add style guidelines
  contribution/style.md
Labels: documentation

#2 Add --version flag
  include/kush/configuration.h
  source/compiler.c
Labels: enhancement

#6 Updated the lexer to recognize keywords correctly.
  source/lexer.c
  source/token.c
Labels: bug

#7 Fix the analyzer
  CMakeLists.txt
  include/kush/analyzer.h
  include/kush/context.h
  include/kush/error-handler.h
  include/kush/scope.h
  include/kush/token-stream.h
  source/analyzer.c
  source/compiler.c
  source/context.c
  source/kush.g4
  source/lexer.c
  source/parser.c
  source/scope.c
  source/symbol-loader.c
  source/token-stream.c
Labels: bug, enhancement

#9 Implement C generator
  CMakeLists.txt
  build_modules
  include/kush/analyzer.h
  include/kush/configuration.h
  include/kush/context.h
  include/kush/error-handler.h
  include/kush/generator.h
  include/kush/parser.h
  module/kush/error.kush
  source/analyzer.c
  source/compiler.c
  source/context.c
  source/generator.c
  source/parser.c
Labels: enhancement

#11 Analyze array and object creations expressions
  include/kush/context.h
  include/kush/error-handler.h
  source/analyzer.c
  source/compiler.c
  source/context.c
  source/generator.c
  source/parser.c
Labels: enhancement

#13 Update the generator and implement the runtime
  include/kush/analyzer.h
  include/kush/compiler.h
  include/kush/context.h
  include/kush/error-handler.h
  include/kush/generator.h
  include/kush/parser.h
  runtime/kush-runtime.c
  runtime/kush-runtime.h
  source/analyzer.c
  source/compiler.c
  source/context.c
  source/generator.c
  source/lexer.c
  source/parser.c
  source/token-stream.c
  source/token.c
Labels: enhancement

#18 Added an example of heap sort.
  example/heap-sort.kush
  source/generator.c
Labels: documentation
